version: "3.7"
services:
  
  db:
    image: postgres:11.5
    container_name: dev_postgres
    environment:
      - POSTGRES_DB=dev_local
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  db_test:
    image: postgres:11.5
    container_name: test_postgres
    environment:
      - POSTGRES_DB=dev_test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin
    ports:
      - 5433:5432