version: "3.7"
services:
  
  naru_db:
    image: postgres:11.5
    container_name: naru_postgres
    environment:
      - POSTGRES_DB=naru_local
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  naru_db_test:
    image: postgres:11.5
    container_name: naru_postgres_test
    environment:
      - POSTGRES_DB=naru_test
      - POSTGRES_PASSWORD=adminpw
      - POSTGRES_USER=admin
    ports:
      - 5433:5432